# 共通の設定を定義する
spring:
    profiles:
        # デフォルトを明示的に指定する
        # 開発環境以外は環境変数でプロファイルを切り替える
        default: development
        active: development
    # DBの設定
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: docker
    # Migrationの設定
    flyway:
      enabled: true
      baseline-on-migrate: true
    thymeleaf:
      cache: true
      # HTML5モードが非推奨になったのでHTMLモードにする
      mode: HTML
    resources:
      # 静的コンテンツをキャッシュする
      cache:
        period: 604800
    
# Doma2
doma:
    # 方言の設定
    dialect: postgres
    # 小文字のスネークケースに変換する（firstName → first_name）
    naming: SNAKE_LOWER_CASE
    
management:
    endpoints:
       web:
          exposure:
            inc lude: info,health,prometheus
